name: deploy-prod
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER_MION }}
          username: ${{ secrets.SSH_USER_MION }}
          password: ${{ secrets.SSH_PASSWORD_MION }}
          port: ${{ secrets.SSH_PORT_MION }}
          script: |
            cd /var/www/html/pageMION
            git fetch 
            git pull origin main
